### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BalajiJBcs** [saumyau/IP#1]
The code good and easy to understand. Here is the comment 

- asset files are not properly ordered in the respective folder. 
- Flask MVC models are not followed, you should not create several '.html' to create template
- The login page is not well built, forms are not global CSRF protected, use flask-WTF.
- Having several .css is code nightmare, creating one over other for each page, is very difficult to make t 
  the update on. I couldn't find one global.css 
- Use the package manager to handle dependency like charts, full calendar

**Comment by saumyau** [comment]
This is not full code, some changes are yet to be made.  And as for the login code, it's a simplistic version just for representation purposes. Thanks for the review.
